### ISSUE TITLE
关于标签链接

### ISSUE THREAD

**Issue by mxdlsm** [Rozbo/hexo-abbrlink#31]
大佬，我现在只有文章不是中文的，标签页和分类页面怎么也让他变成不是中文呀？求帮助。

**Comment by ohroy** [comment]
这个hexo没有提供对应的api，应是实现不了。

**Comment by yansheng836** [comment]
其实这个问题hexo官方自带解决方法，详见：<https://hexo.io/zh-cn/docs/configuration.html#%E5%88%86%E7%B1%BB-amp-%E6%A0%87%E7%AD%BE>

截个图：
![image](https://user-images.githubusercontent.com/45334066/68354504-89893d80-0147-11ea-8bc4-cf90c2531475.png)


站点的配置文件有`category_map`和`tag_map`配置，即分类和标签的别名（映射），举个例子：
```yml
# Category & Tag
default_category: uncategorized
category_map:
    编程: programming
tag_map:
    生活: life
```
这样标签`生活`的访问网址为：<http://localhost:4000/tags/life/>，分类同理。
