### ISSUE TITLE
連結成功生成後，本地預覽、上傳後開起來一片空白，

### ISSUE THREAD

**Issue by TillMac** [Rozbo/hexo-abbrlink#53]
大神你好，小弟不才，頭一次接觸 hexo ，也不太會寫碼

按照您給的方法後添加配置：

```
permalink: posts/:abbrlink.html
# abbrlink config
abbrlink:
  alg: crc32  # 算法：crc16(default) and crc32
  rep: hex    # 进制：dec(default) and hex 
```

生成連結開啟後卻是一片空白，檢查本地的 deploy.git\posts ，有文章檔案，但裡面一片空白，沒有任何程式碼，在網路上爬了許久，仍找不到解決辦法，故上來請教。

不曉得視插件的問題，還是其他問題呢？

還請多多擔待，謝謝您！
